name: "Publish every Git push to main to FlakeHub"
on:
  push:
    branches:
      - "main"
jobs:
  flakehub-publish:
    runs-on: "ubuntu-latest"
    permissions:
      id-token: "write"
      contents: "read"
    steps:
      - uses: "actions/checkout@v3"
      - name: Check Nix flake inputs
        uses: DeterminateSystems/flake-checker-action@v4
      - uses: "DeterminateSystems/nix-installer-action@main"
      - uses: DeterminateSystems/magic-nix-cache-action@main
      - name: Build default package
        run: nix build
      - uses: "DeterminateSystems/flakehub-push@main"
        with:
          name: "specCon18/YUNODO"
          rolling: true
          visibility: "public"
